### PR TITLE
Adds fullscreen button.  Kinda hacky but it works :)

### PR DESCRIPTION
**Pull request by jqnatividad**
Maybe we can use something like https://github.com/bdougherty/BigScreen.

In general, I wish allowfullscreen was standard for resource views - https://github.com/ckan/ckan/issues/2230

### CODE REVIEW

**Comment by rossjones** [comment]
@jqnatividad  Works great - thank you.  The button is possibly in the wrong place, but I think the Embed button could also do with being in a different place.  

I doubt I am going to get more time to work on this, but I'm happy to transfer the repo to you if you'd like it?  Easier to do that than have a fork and have people get confused.

**Comment by jqnatividad** [comment]
Up to you @rossjones.  I was planning on making it auto-detect MS Office files, make it work with OpenOffice (it turns out it can open OO files as well) and at least localize the fullscreen button and see if there's a way to localize the viewer too.

**Comment by rossjones** [comment]
Unfortunately I can't transfer to you whilst you have an existing repo with the same name.  Let me know if there's another account or organisation I can transfer to and I'll do that.

**Comment by jqnatividad** [comment]
I deleted my fork.  Try it now :smile:

**Comment by jqnatividad** [comment]
Thanks! Will be sure to keep it updated.

**Pull request merged**
